### ISSUE TITLE
Fix "We found a potential security vulnerability in one of your dependencies." from GitHub

### ISSUE THREAD

**Issue by aashish24** [kitware-data-solutions/miqa-phase1#40]

**Comment by scottwittenburg** [comment]
At the time @aashish24 created this issue, I believe the potential vulnerability was with `highlight.js`, and was assigned "moderate" severity.  It looks like this vulnerability can be fixed by simply re-running the `npm install` and committing the resulting `package-lock.json`.

Yesterday, a new potential vulnerability was discovered with `axios`, which was assigned "high" severity.  In order to pick up the fixed version, we may need `girder/girder-web-components` and `InsightSoftwareConsortium/itk-js` to update their dependency on `axios`.

**Comment by thewtex** [comment]
`itk` 13.3.1 has the updated `axios`

**Comment by aashish24** [comment]
@scottwittenburg @thewtex has updated axios, do we need to get new version of GWC?

**Comment by scottwittenburg** [comment]
I think most, if not all, of these vulnerabilities are fixed in #91
